In [1]:
# Importing libraries
import numpy as np
import pandas as pd

In [2]:
# Loading in productivity data
gdpPerHoursWorked = pd.read_csv('RawData/gdp_over_hours_worked_with_estimated_hours_worked.csv')

In [4]:
gdpPerHoursWorked.head(20)

,year,iso3c,country,iso2c,pop,labor_force,gdp_ppp_c,gdp_ppp,gdp,gdp_c,...,hours_worked_over_pop_modelled,use_model,estimated_using_past_value,estimated_using_model,is_grouping,hours_worked_KNOWN_PLUS_ESTIMATED,hour_worked_adjustment,hours_worked_adjustment,gdp_ppp_over_pop_adjusted_for_hours,gdp_ppp_over_population_15_to_65
0,1950,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
1,1950,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
2,1950,AIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
3,1950,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
4,1950,ARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
5,1950,ARG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,786.479318,False,False,False,False,NaN,NaN,NaN,NaN,NaN
6,1950,ARM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
7,1950,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
8,1950,AUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,891.297337,False,False,False,False,NaN,NaN,NaN,NaN,NaN
9,1950,AUT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,876.878951,False,False,False,False,NaN,NaN,NaN,NaN,NaN
10,1950,AZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
11,1950,BDI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
12,1950,BEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,839.630572,False,False,False,False,NaN,NaN,NaN,NaN,NaN
13,1950,BEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
14,1950,BFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
15,1950,BGD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
16,1950,BGR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
17,1950,BHR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
18,1950,BHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN
19,1950,BIH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,False,True,False,NaN,NaN,NaN,NaN,NaN

In [5]:
gdpPerHoursWorked.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16833 entries, 0 to 16832
Data columns (total 53 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   year                                 16833 non-null  int64
 1   iso3c                                16833 non-null  object
 2   country                              11223 non-null  object
 3   iso2c                                11180 non-null  object
 4   pop                                  11213 non-null  float64
 5   labor_force                          7617 non-null   float64
 6   gdp_ppp_c                            7530 non-null   float64
 7   gdp_ppp                              7572 non-null   float64
 8   gdp                                  10028 non-null  float64
 9   gdp_c                                9785 non-null   float64
 10  unemployment_r                       7384 non-null   float64
 11  pop_over_65                          11223 non-null  float64
 12  working_age_pop_pct                  2279 non-null   float64
 13  employment_rate                      970 non-null    float64
 14  hours_worked                         1612 non-null   float64
 15  total_hours                          1556 non-null   float64
 16  hours_per_employed                   1553 non-null   float64
 17  employed                             1553 non-null   float64
 18  total_hours_alternative              934 non-null    float64
 19  gdp_over_k_hours_worked              1531 non-null   float64
 20  gdp_ppp_over_k_hours_worked          1292 non-null   float64
 21  gdp_over_pop                         10028 non-null  float64
 22  gdp_ppp_over_pop                     7572 non-null   float64
 23  gdp_ppp_over_labor_force             7060 non-null   float64
 24  gdp_ppp_over_pop_c                   7530 non-null   float64
 25  gdp_over_pop_c                       9785 non-null   float64
 26  gdp_ppp_over_k_hours_worked_c        1292 non-null   float64
 27  continent                            9245 non-null   float64
 28  region                               9245 non-null   float64
 29  penn_pop                             10399 non-null  float64
 30  penn_employment                      9529 non-null   float64
 31  penn_average_hours_worked            3492 non-null   float64
 32  penn_employment_prop                 9529 non-null   float64
 33  penn_hours_worked_over_pop           3492 non-null   float64
 34  pop_0_to_14                          2871 non-null   float64
 35  pop_15_to_64                         2871 non-null   float64
 36  labor_force_partic_ILO               2533 non-null   float64
 37  labor_force_partic_ILO_female        2533 non-null   float64
 38  pop_percent_male                     2871 non-null   float64
 39  oil                                  16833 non-null  float64
 40  hours_worked_over_pop                1556 non-null   float64
 41  hours_worked_over_pop_combined       16661 non-null  float64
 42  hours_worked_over_pop_predicted      16833 non-null  float64
 43  hours_worked_over_pop_modelled       3621 non-null   float64
 44  use_model                            16833 non-null  bool
 45  estimated_using_past_value           16833 non-null  bool
 46  estimated_using_model                16833 non-null  bool
 47  is_grouping                          16833 non-null  bool
 48  hours_worked_KNOWN_PLUS_ESTIMATED    11051 non-null  float64
 49  hour_worked_adjustment               0 non-null      float64
 50  hours_worked_adjustment              771 non-null    float64
 51  gdp_ppp_over_pop_adjusted_for_hours  690 non-null    float64
 52  gdp_ppp_over_population_15_to_65     2608 non-null   float64
dtypes: bool(4), float64(45), int64(1), object(3)
memory usage: 6.4+ MB

In [6]:
# Cut down data to desired years, desired countries, and needed columns. Find definitions for column names
countryCodes = [
    'AUS', 'AUT', 'BEL', 'CAN', 'HRV', 
    'CZE', 'DNK', 'EST', 'FIN', 'FRA', 
    'DEU', 'GRC', 'HUN', 'ISL', 'ISR', 
    'ITA', 'JPN', 'KOR', 'LVA', 'LTU', 
    'LUX', 'NLD', 'NZL', 'NOR', 'POL', 
    'PRT', 'SVK', 'SVN', 'ESP', 'SWE', 
    'CHE', 'GBR', 'USA'
]
gdpPerHourFilter = gdpPerHoursWorked[(gdpPerHoursWorked['year'] > 2006) & (gdpPerHoursWorked['iso3c'].isin(countryCodes))]

In [11]:
gdpPerHourFilter.info()

<class 'pandas.core.frame.DataFrame'>
Index: 528 entries, 12632 to 16818
Data columns (total 53 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   year                                 528 non-null    int64
 1   iso3c                                528 non-null    object
 2   country                              528 non-null    object
 3   iso2c                                528 non-null    object
 4   pop                                  528 non-null    float64
 5   labor_force                          528 non-null    float64
 6   gdp_ppp_c                            528 non-null    float64
 7   gdp_ppp                              528 non-null    float64
 8   gdp                                  528 non-null    float64
 9   gdp_c                                528 non-null    float64
 10  unemployment_r                       528 non-null    float64
 11  pop_over_65                          528 non-null    float64
 12  working_age_pop_pct                  528 non-null    float64
 13  employment_rate                      512 non-null    float64
 14  hours_worked                         527 non-null    float64
 15  total_hours                          524 non-null    float64
 16  hours_per_employed                   524 non-null    float64
 17  employed                             524 non-null    float64
 18  total_hours_alternative              511 non-null    float64
 19  gdp_over_k_hours_worked              524 non-null    float64
 20  gdp_ppp_over_k_hours_worked          524 non-null    float64
 21  gdp_over_pop                         528 non-null    float64
 22  gdp_ppp_over_pop                     528 non-null    float64
 23  gdp_ppp_over_labor_force             528 non-null    float64
 24  gdp_ppp_over_pop_c                   528 non-null    float64
 25  gdp_over_pop_c                       528 non-null    float64
 26  gdp_ppp_over_k_hours_worked_c        524 non-null    float64
 27  continent                            528 non-null    float64
 28  region                               528 non-null    float64
 29  penn_pop                             429 non-null    float64
 30  penn_employment                      429 non-null    float64
 31  penn_average_hours_worked            429 non-null    float64
 32  penn_employment_prop                 429 non-null    float64
 33  penn_hours_worked_over_pop           429 non-null    float64
 34  pop_0_to_14                          363 non-null    float64
 35  pop_15_to_64                         363 non-null    float64
 36  labor_force_partic_ILO               363 non-null    float64
 37  labor_force_partic_ILO_female        363 non-null    float64
 38  pop_percent_male                     363 non-null    float64
 39  oil                                  528 non-null    float64
 40  hours_worked_over_pop                524 non-null    float64
 41  hours_worked_over_pop_combined       528 non-null    float64
 42  hours_worked_over_pop_predicted      528 non-null    float64
 43  hours_worked_over_pop_modelled       528 non-null    float64
 44  use_model                            528 non-null    bool
 45  estimated_using_past_value           528 non-null    bool
 46  estimated_using_model                528 non-null    bool
 47  is_grouping                          528 non-null    bool
 48  hours_worked_KNOWN_PLUS_ESTIMATED    528 non-null    float64
 49  hour_worked_adjustment               0 non-null      float64
 50  hours_worked_adjustment              99 non-null     float64
 51  gdp_ppp_over_pop_adjusted_for_hours  99 non-null     float64
 52  gdp_ppp_over_population_15_to_65     363 non-null    float64
dtypes: bool(4), float64(45), int64(1), object(3)
memory usage: 208.3+ KB

In [36]:
gdpPerHourFilter[(gdpPerHourFilter['oil'] == 0.0)][['country', 'year']]

               country  year
12633          Austria  2007
12636          Belgium  2007
12656      Switzerland  2007
12673          Czechia  2007
12674          Germany  2007
...                ...   ...
16758           Poland  2022
16762         Portugal  2022
16789  Slovak Republic  2022
16790         Slovenia  2022
16791           Sweden  2022

[416 rows x 2 columns]

In [47]:
gdpPerHourLessColumns = gdpPerHourFilter.drop(['pop_0_to_14', 'pop_15_to_64', 'labor_force_partic_ILO', 'labor_force_partic_ILO_female', 
                                               'pop_percent_male', 'hour_worked_adjustment', 'hours_worked_adjustment', 'gdp_ppp_over_pop_adjusted_for_hours', 
                                               'gdp_ppp_over_population_15_to_65', 'iso2c', 'penn_pop', 'penn_employment', 'penn_average_hours_worked', 
                                               'penn_employment_prop', 'total_hours_alternative', 'oil', 'use_model', 'estimated_using_past_value', 
                                               'estimated_using_model', 'is_grouping', 'hours_worked_KNOWN_PLUS_ESTIMATED', 'region', 'pop_over_65',
                                               'working_age_pop_pct', 'employment_rate', 'employed', 'unemployment_r' ], axis=1)

In [48]:
gdpPerHourLessColumns.reset_index(drop=True)

,year,iso3c,country,pop,labor_force,gdp_ppp_c,gdp_ppp,gdp,gdp_c,hours_worked,...,gdp_ppp_over_labor_force,gdp_ppp_over_pop_c,gdp_over_pop_c,gdp_ppp_over_k_hours_worked_c,continent,penn_hours_worked_over_pop,hours_worked_over_pop,hours_worked_over_pop_combined,hours_worked_over_pop_predicted,hours_worked_over_pop_modelled
0,2007,AUS,Australia,20827622.0,10937240.0,9.186995e+11,7.628943e+11,8.544273e+11,1.095250e+12,1803.000000,...,69751.995589,44109.669374,52586.409390,47828.591243,5.0,895.758812,922.244796,922.244796,910.891221,922.244796
1,2007,AUT,Austria,8295487.0,4201262.0,4.360529e+11,3.271376e+11,3.891856e+11,3.644847e+11,1606.428996,...,77866.496956,52565.073969,43937.712891,67645.310343,4.0,829.445365,777.069005,777.069005,751.812698,777.069005
2,2007,BEL,Belgium,10625700.0,4728844.0,5.163070e+11,3.909816e+11,4.709222e+11,4.281119e+11,1593.657532,...,82680.171532,48590.400535,40290.227756,73741.553706,4.0,658.800675,658.928353,658.928353,751.812698,658.928353
3,2007,CAN,Canada,32889025.0,18382598.0,1.509263e+12,1.301593e+12,1.468820e+12,1.384576e+12,1745.000000,...,70805.734407,45889.562129,42098.431220,50845.133236,2.0,898.870758,902.535980,902.535980,872.685869,902.535980
4,2007,CHE,Switzerland,7551117.0,4307257.0,4.924324e+11,3.845359e+11,4.907547e+11,6.135597e+11,1668.900000,...,89276.283797,65213.180537,81254.170050,69663.070107,4.0,943.117746,936.122689,936.122689,814.328625,936.122689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,2022,PRT,Portugal,10379007.0,5289425.0,3.710120e+11,4.302266e+11,2.519454e+11,2.295083e+11,1635.095304,...,81337.120926,35746.391474,22112.743760,44805.232401,4.0,NaN,797.817343,797.817343,777.020260,797.817343
524,2022,SVK,Slovak Republic,5431752.0,2826275.0,1.801833e+11,2.034706e+11,1.154688e+11,1.025282e+11,1622.066850,...,71992.489044,33172.225796,18875.706750,45763.884192,4.0,NaN,724.855995,724.855995,764.977349,724.855995
525,2022,SVN,Slovenia,2108732.0,1060410.0,8.893620e+10,1.055034e+11,6.211777e+10,5.496767e+10,1619.012873,...,99492.983288,42175.203206,26066.691386,50930.025561,4.0,NaN,828.100963,828.100963,777.954197,828.100963
526,2022,SWE,Sweden,10486941.0,5600661.0,5.748773e+11,6.772298e+11,5.859392e+11,5.818365e+11,1440.459124,...,120919.625775,54818.396547,55482.000725,76795.931188,4.0,NaN,713.819023,713.819023,732.275790,713.819023
527,2022,USA,United States,333287557.0,169229171.0,2.156470e+13,2.546270e+13,2.546270e+13,2.095269e+13,1810.944000,...,150462.830076,64702.978311,62866.714391,76150.654655,2.0,NaN,849.670677,849.670677,806.052763,849.670677

In [49]:
gdpPerHourLessColumns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 528 entries, 12632 to 16818
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   year                             528 non-null    int64
 1   iso3c                            528 non-null    object
 2   country                          528 non-null    object
 3   pop                              528 non-null    float64
 4   labor_force                      528 non-null    float64
 5   gdp_ppp_c                        528 non-null    float64
 6   gdp_ppp                          528 non-null    float64
 7   gdp                              528 non-null    float64
 8   gdp_c                            528 non-null    float64
 9   hours_worked                     527 non-null    float64
 10  total_hours                      524 non-null    float64
 11  hours_per_employed               524 non-null    float64
 12  gdp_over_k_hours_worked          524 non-null    float64
 13  gdp_ppp_over_k_hours_worked      524 non-null    float64
 14  gdp_over_pop                     528 non-null    float64
 15  gdp_ppp_over_pop                 528 non-null    float64
 16  gdp_ppp_over_labor_force         528 non-null    float64
 17  gdp_ppp_over_pop_c               528 non-null    float64
 18  gdp_over_pop_c                   528 non-null    float64
 19  gdp_ppp_over_k_hours_worked_c    524 non-null    float64
 20  continent                        528 non-null    float64
 21  penn_hours_worked_over_pop       429 non-null    float64
 22  hours_worked_over_pop            524 non-null    float64
 23  hours_worked_over_pop_combined   528 non-null    float64
 24  hours_worked_over_pop_predicted  528 non-null    float64
 25  hours_worked_over_pop_modelled   528 non-null    float64
dtypes: float64(23), int64(1), object(2)
memory usage: 127.5+ KB

In [50]:
gdpPerHourLessColumns.to_csv('gdp_per_hour_worked_filtered.csv')